name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Brickie
    steps:
      - uses: actions/checkout@v2
      - name: AppBrickie
        id: appBrickieBuild
        uses: DarthBenro008/app-brickie@v3.0
        with:
          type: "native"
          chatid: "bt2koqahuckbaa0mh2j0"
          packagename: "Gakko"
          firebase: ${{ secrets.FIREBASE }}
          keystore: ${{ secrets.KEYSTORE }}
          keystorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEYSTORE_PASS }}
      - name: Get Automated Result
        run: echo "${{ steps.appBrickieBuild.outputs.result }}"
